#!/usr/bin/env python3
"""Plain-language entry path added to the preserved technical Wiki.
Run from project root after build_wiki07.py. No CDN or third-party runtime.
"""
from pathlib import Path
from bs4 import BeautifulSoup
import html
P=Path('app/static')
soup=BeautifulSoup((P/'wiki07.html').read_text(),'html.parser')
soup.title.string='Flytrade | Wiki : commencer simplement'
soup.select_one('.brand span').string='ALPHA 08 / COMPRENDRE & EXPERIMENTER'
soup.head.append(soup.new_tag('link',rel='stylesheet',href='/static/clarity08.css'))
soup.select_one('script')['src']='/static/wiki08.js'
guide=soup.new_tag('a',href='/guide',attrs={'class':'button'});guide.string='Tutoriel';soup.select_one('header nav').append(guide)
chapters=[]
def ch(key,title,body):chapters.append((key,html.unescape(title),body))
ch('debut','Commencer sans pr&eacute;requis',r'''
<h1>Bienvenue. Ce que Flytrade fait, en mots simples.</h1>
<p>Flytrade est un laboratoire sur ton ordinateur. Il observe un prix, propose trois zones que ce prix pourrait toucher et apprend sur des exemples pass&eacute;s. Il peut ensuite essayer ses choix dans un jeu d'argent <strong>fictif</strong>. Le nom &laquo; cerveau de mouche &raquo; est un raccourci : aucun cerveau vivant n'est branch&eacute; au programme. Les unit&eacute;s sont des calculs inspir&eacute;s de certains circuits de la drosophile.</p>
<div class="plain08"><h2>Le chemin le plus simple</h2><p><strong>R&eacute;colter des exemples &rarr; pr&eacute;parer une exp&eacute;rience &rarr; apprendre &rarr; v&eacute;rifier &rarr; copier vers le march&eacute;.</strong> Ces &eacute;tapes sont distinctes. Le tutoriel montre les boutons, sans les cliquer &agrave; ta place.</p><a class="button" href="/guide">Ouvrir le tutoriel</a></div>
<h2>Ce que tu regardes sur le march&eacute;</h2><p>La courbe est le prix d'ETH en dollars sur la source choisie. Les lignes d&eacute;coupent le temps en cases de cinq secondes et le prix en bandes de cinquante cents. Trois cases sont envisag&eacute;es : la bande actuelle, celle au-dessus et celle en dessous, dans une colonne future. Un choix r&eacute;ussit si une transaction observ&eacute;e entre dans sa case pendant les cinq secondes pr&eacute;vues.</p>
<p>&laquo; Stable &raquo; ne veut pas dire que le prix ne bouge jamais. Cela veut dire que la bande centrale est touch&eacute;e. &laquo; Attendre &raquo; signifie qu'aucune mise n'est engag&eacute;e. Le prix peut toucher plusieurs cases pendant la m&ecirc;me fen&ecirc;tre, ou aucune. Les trois r&eacute;sultats ne sont donc pas trois classes forc&eacute;ment exclusives.</p>
<h2>Deux copies du cerveau</h2><p><strong>Dans l'atelier</strong>, les poids changent pendant l'apprentissage. <strong>Sur le march&eacute;</strong>, une copie reste gel&eacute;e : elle calcule des choix sans se r&eacute;&eacute;crire apr&egrave;s chaque gain ou perte. Une s&eacute;ance d'entra&icirc;nement ne remplace pas spontan&eacute;ment le cerveau du march&eacute;. Le transfert est un bouton distinct, avec confirmation.</p>
<p>Le bandeau sup&eacute;rieur montre l'identifiant des poids et le nombre de corrections de chaque copie. Des identifiants identiques juste apr&egrave;s transfert indiquent les m&ecirc;mes poids de pr&eacute;vision. Ils ne sont ni un certificat de qualit&eacute; ni l'identit&eacute; d'un animal. L'identifiant n'englobe pas tout l'historique ni les poids de la sortie &eacute;conomique auxiliaire.</p>
<h2>R&eacute;el ou simul&eacute; ?</h2><p>Les transactions viennent de la place choisie lorsqu'elle est connect&eacute;e. Les connexions neuronales, les multiplicateurs et le portefeuille sont ceux de notre simulateur. Aucun ordre r&eacute;el n'est envoy&eacute; &agrave; Euphoria. Un b&eacute;n&eacute;fice avec un multiplicateur invent&eacute; peut signaler une faiblesse du simulateur, pas une capacit&eacute; &agrave; gagner sur une plateforme.</p>
<p>Commence par <a href="#debut-objets">les objets</a>, puis <a href="#debut-experience">la premi&egrave;re exp&eacute;rience</a>. Les formules d&eacute;taill&eacute;es sont conserv&eacute;es dans les chapitres techniques. Tu peux les lire apr&egrave;s avoir compris le parcours.</p>
<p class="muted">Base : le code du projet fourni, compl&eacute;t&eacute; par les nouvelles actions d'alpha 08. Aucune capacit&eacute; biologique ou financi&egrave;re suppl&eacute;mentaire n'est pr&eacute;sum&eacute;e.</p>''')
ch('debut-objets','Les mots qui pr&ecirc;tent &agrave; confusion',r'''
<h1>Les objets du laboratoire ne sont pas interchangeables.</h1>
<div class="step-grid"><div><h2>Collecte : le cahier brut</h2><p>Ce que le programme enregistre : transactions, capteurs et fen&ecirc;tres termin&eacute;es. D&eacute;marrer la collecte ne fait apprendre aucun cerveau. Fermer l'onglet ne l'arr&ecirc;te pas si le serveur reste actif.</p></div><div><h2>Corpus : la bo&icirc;te d'exercices</h2><p>La liste d'observations valides disponible dans l'atelier. Copier la collecte dans le corpus ajoute les nouvelles fen&ecirc;tres termin&eacute;es. Les doublons ne deviennent pas des exemples suppl&eacute;mentaires.</p></div><div><h2>Cerveau : calculs et m&eacute;moire</h2><p>L'architecture et les poids appris. Un cerveau initial n'a re&ccedil;u aucune correction. Il peut d&eacute;j&agrave; produire des activations : vierge ne signifie pas que tous ses nombres sont nuls.</p></div><div><h2>Protocole : le plan</h2><p>Quels exercices, dans quel ordre, combien de fois et avec quels r&eacute;glages. Ce plan est distinct du cerveau qui le suit. Pr&eacute;parer le protocole ne le lance pas.</p></div></div>
<h2>S&eacute;ance, exemple et passage</h2><p>Une <strong>s&eacute;ance</strong> est une ex&eacute;cution identifi&eacute;e d'un protocole avec un cerveau. Un <strong>exemple</strong> contient un pass&eacute; visible et une correction future que l'environnement garde cach&eacute;e avant le choix. Un <strong>passage</strong> consiste &agrave; revoir un ensemble d'exemples. Dix passages sur cent exemples restent cent situations uniques, pr&eacute;sent&eacute;es mille fois.</p>
<h2>Poids, param&egrave;tres et calibration</h2><p>Les <strong>poids</strong> sont la m&eacute;moire modifi&eacute;e par les corrections. Les <strong>param&egrave;tres</strong> sont tes choix d'exp&eacute;rience, comme la vitesse des corrections ou le nombre de KC. La <strong>calibration</strong> relie les scores d'un cerveau fixe aux fr&eacute;quences de touche observ&eacute;es sur d'autres exemples. Elle doit correspondre aux poids qui l'ont produite.</p>
<p>Image utile : l'architecture est la forme d'un instrument ; les poids sont son r&eacute;glage appris ; la calibration contr&ocirc;le ses indications. Ce n'est qu'une analogie. Changer les poids puis garder l'ancienne calibration reviendrait &agrave; utiliser le contr&ocirc;le d'un autre instrument.</p>
<h2>Quel fichier va o&ugrave; ?</h2><p><code>windows.jsonl</code> contient des observations et se charge dans le corpus. Un fichier de <strong>poids JSON</strong> conserve le cerveau et sa calibration : ce n'est pas un jeu d'exercices. Un <strong>rapport</strong> explique le protocole et ses r&eacute;sultats. Une <strong>archive de s&eacute;ance</strong> garde poids, plan, calibration et compteurs au moment d'un remplacement.</p>
<p>Les archives r&eacute;centes sont t&eacute;l&eacute;chargeables dans l'atelier. La restauration d'une archive quelconque n'est pas automatis&eacute;e dans cette version. Pour retrouver une installation enti&egrave;re, la proc&eacute;dure de sauvegarde restaure code et donn&eacute;es ensemble. Ne remplace pas un fichier de base pendant son utilisation.</p>
<p class="muted">Impl&eacute;mentation : academy06.py, academy08.py, run08.py ; <a href="#exploitation">stockage et sauvegardes</a>.</p>''')
ch('debut-neurones','Comprendre les neurones sans formules',r'''
<h1>Pourquoi des petites cases s'allument-elles ?</h1>
<p>Les cases repr&eacute;sentent des nombres calcul&eacute;s. Un nombre plus grand est dessin&eacute; plus lumineux. Ce n'est pas une microscopie, une tension &eacute;lectrique ou une mesure de dopamine. Cette carte ne mesure pas le &laquo; bonheur &raquo; de la mouche.</p>
<h2>PN : transformer les capteurs</h2><p>Le programme ne lit pas les pixels de la courbe. Il calcule des valeurs &agrave; partir du pass&eacute; : variation r&eacute;cente, position dans la bande, agitation et &eacute;ventuellement carnet d'ordres. Plusieurs unit&eacute;s PN r&eacute;agissent &agrave; diff&eacute;rentes valeurs d'un m&ecirc;me capteur. C'est une mani&egrave;re de transformer les chiffres d'entr&eacute;e en une repr&eacute;sentation utilisable ensuite.</p>
<h2>KC : combiner les indices</h2><p>Une Kenyon cell synth&eacute;tique re&ccedil;oit une petite combinaison d'entr&eacute;es. Certaines combinaisons s'activent davantage dans un contexte, d'autres dans un autre. Aucune KC ne porte une consigne humaine &laquo; cette forme signifie hausse &raquo;. Les connexions d'entr&eacute;e sont tir&eacute;es avec une graine et restent fixes. Les poids de lecture en sortie sont modifiables.</p>
<h2>APL : ne pas tout laisser s'allumer</h2><p>Notre APL est un seuil global. Avec une fraction active de 5 %, environ cinq KC sur cent restent actives pour un candidat. Pour 2 048 KC, cela fait environ 103 cases, avec de petites variations possibles. Un autre contexte peut activer un autre ensemble. La vue cumul&eacute;e montre l'utilisation dans le temps ; la vue instantan&eacute;e montre le dernier calcul.</p>
<p>L'objectif n'est pas d'allumer le maximum. Il faut des repr&eacute;sentations assez distinctes pour s&eacute;parer les situations, tout en partageant de l'information utile entre situations proches. Cinq pour cent est un choix d'ing&eacute;nierie, pas une valeur parfaite d&eacute;montr&eacute;e pour les march&eacute;s.</p>
<h2>MBON : lire la m&eacute;moire</h2><p>Les sorties MBON-like combinent les activations KC et les poids appris. Le m&ecirc;me syst&egrave;me est &eacute;valu&eacute; pour chaque candidat : hausse, stable et baisse. &laquo; Like &raquo; signifie inspir&eacute; de. Un MBON biologique ne correspond pas naturellement &agrave; &laquo; acheter de l'ETH &raquo;.</p>
<h2>DAN : permettre une correction</h2><p>Apr&egrave;s la fermeture de la fen&ecirc;tre, l'erreur entre l'attente et le r&eacute;sultat guide la modification des poids. PAM et PPL1 nomment nos modules app&eacute;titifs et aversifs d'inspiration. Ils ne re&ccedil;oivent pas une vraie hormone. Une barre peut montrer un signal sans que les poids changent : sur le march&eacute;, les poids sont gel&eacute;s.</p>
<p>La recherche relie les repr&eacute;sentations KC, les signaux dopaminergiques et les sorties MBON &agrave; l'apprentissage associatif chez la drosophile. Flytrade en fait une approximation ; il n'importe ni les synapses ni la g&eacute;om&eacute;trie de MaleCNS. <a href="#s1">Source scientifique S1</a>. Les formules exactes du programme sont dans <a href="#neurones">PN/KC/APL</a>, <a href="#motifs">motifs</a> et <a href="#plasticite">plasticit&eacute;</a>.</p>
<h2>Un r&eacute;sum&eacute; pratique</h2><p>PN d&eacute;crit des indices ; KC forme des combinaisons ; MBON lit ce qui a &eacute;t&eacute; appris ; DAN guide les corrections. Ce vocabulaire aide &agrave; suivre le calcul, pas &agrave; attribuer une compr&eacute;hension humaine &agrave; chaque unit&eacute;. Le cerveau complet d'un animal comporte bien d'autres m&eacute;canismes qui ne sont pas simul&eacute;s ici.</p>''')
ch('debut-experience','Ma premi&egrave;re exp&eacute;rience, pas &agrave; pas',r'''
<h1>Du cahier de donn&eacute;es au cerveau utilisable.</h1>
<h2>1. Rassembler les exercices</h2><p>Ouvre Collecte &amp; apprentissage. La collecte enregistre le march&eacute; dans son cahier. Clique ensuite Copier la collecte dans le corpus pour donner les fen&ecirc;tres termin&eacute;es &agrave; l'atelier. Tu peux aussi importer un export JSONL. Beaucoup de transactions et beaucoup de fen&ecirc;tres sont deux effectifs diff&eacute;rents : plusieurs transactions appartiennent &agrave; un exercice.</p>
<p>V&eacute;rifie la source active : Kraken et Coinbase ne sont pas interchangeables. Quand les capteurs de liquidit&eacute; sont activ&eacute;s, les fen&ecirc;tres sans carnet utilisable sont filtr&eacute;es. Le total utilisable peut donc &ecirc;tre plus petit que le corpus.</p>
<h2>2. V&eacute;rifier avant de modifier</h2><p>Dans Pr&eacute;parer, clique V&eacute;rifier les donn&eacute;es. Cela lit les exemples et affiche les effectifs, sans modifier le cerveau ni la s&eacute;ance. Regarde le nombre de fen&ecirc;tres de calibration et l'avertissement sur des exemples de test d&eacute;j&agrave; consult&eacute;s.</p>
<p>Les donn&eacute;es sont s&eacute;par&eacute;es chronologiquement avant l'&eacute;quilibrage. Le programme retire des exemples aux fronti&egrave;res pour &eacute;viter que leurs historiques et leurs futurs se chevauchent entre groupes. Des exemples en moins ne sont donc pas forc&eacute;ment une erreur. Voir <a href="#dataset">Dataset</a>.</p>
<h2>3. Pr&eacute;parer le cerveau</h2><p>Pr&eacute;parer une nouvelle exp&eacute;rience cr&eacute;e un cerveau neuf avec les r&eacute;glages du formulaire, une calibration vide et le plan d'exercices. L'ancienne s&eacute;ance est archiv&eacute;e. Le corpus, le portefeuille et la copie live restent inchang&eacute;s. La confirmation r&eacute;sume ces effets avant de les appliquer.</p>
<p>Les r&eacute;glages avanc&eacute;s sont repli&eacute;s, pas d&eacute;sactiv&eacute;s. Leurs valeurs servent au protocole. Commence avec une configuration fixe et ne change ensuite qu'un param&egrave;tre &agrave; la fois pour comprendre son effet.</p>
<h2>4. Lancer les corrections</h2><p>D&eacute;marrer / reprendre fait avancer la s&eacute;ance pr&eacute;par&eacute;e. Observer un seul exemple permet de suivre un calcul. Mettre en pause conserve la m&eacute;moire et s'arr&ecirc;te apr&egrave;s le travail engag&eacute;. Reprendre repart de cette position, pas d'un autre cerveau.</p>
<h2>5. Laisser finir la calibration</h2><p>Apr&egrave;s TRAIN, le cerveau passe sur un autre groupe d'exemples sans modifier ses poids. Le programme observe les fr&eacute;quences de touche associ&eacute;es aux groupes de scores. Un score de 0,7 ne signifie pas spontan&eacute;ment 70 % de chances. <a href="#s7">Source de la notion : S7</a>.</p>
<p>Le minimum technique de 60 fen&ecirc;tres, puis de 20 par groupe utilis&eacute;, refuse certaines d&eacute;cisions trop peu document&eacute;es. Il ne garantit ni l'ind&eacute;pendance des exemples ni une bonne performance. Une petite s&eacute;ance peut se terminer sans permettre une mise.</p>
<h2>6. Observer le test puis transf&eacute;rer</h2><p>Le test s'ouvre s&eacute;par&eacute;ment, avec des poids et une calibration qui ne changent pas. Les r&eacute;sultats se comparent aux choix constants sur les m&ecirc;mes fen&ecirc;tres. Utiliser ce cerveau sur le march&eacute; copie ensuite explicitement les poids et la calibration. La copie reste gel&eacute;e et sa session financi&egrave;re repart &agrave; 20 euros fictifs.</p>
<p>Avant transfert, arr&ecirc;te collecte et politique et attends la fin des fen&ecirc;tres ouvertes. Apr&egrave;s transfert, rien ne mise automatiquement. Une fois la politique activ&eacute;e, elle peut attendre en raison du flux, de la calibration ou de l'int&eacute;r&ecirc;t &eacute;conomique estim&eacute;. Ce n'est pas forc&eacute;ment une panne.</p>
<p><a class="button" href="/guide">Voir les boutons dans le tutoriel</a></p>''')
ch('debut-reentrainer','R&eacute;entra&icirc;ner : reprendre, rejouer, continuer',r'''
<h1>Trois besoins, trois commandes.</h1>
<h2>A. Continuer une s&eacute;ance mise en pause</h2><p>Tu es &agrave; l'exemple 37 sur 200 et tu veux aller &agrave; 38. Utilise <strong>Reprendre ma s&eacute;ance</strong>. Le cerveau, le compteur et le plan restent pr&eacute;sents. Les nouveaux exercices ajout&eacute;s au corpus ne sont pas incorpor&eacute;s. Apr&egrave;s red&eacute;marrage, la reprise se fait &agrave; partir de la derni&egrave;re &eacute;tape enregistr&eacute;e.</p>
<h2>B. Refaire exactement la m&ecirc;me exp&eacute;rience depuis z&eacute;ro</h2><p><strong>Rejouer depuis z&eacute;ro</strong> reprend les identifiants des exercices, leur ordre et les r&eacute;glages sauvegard&eacute;s, mais recr&eacute;e un cerveau initial avec la m&ecirc;me graine. L'ancienne s&eacute;ance est archiv&eacute;e et la nouvelle commence en pause. Clique ensuite D&eacute;marrer.</p>
<p>Les champs modifi&eacute;s du formulaire ne changent pas ce bouton. Il rejoue la configuration sauvegard&eacute;e. Pour changer la taille du cerveau ou sa vitesse, modifie le formulaire puis Pr&eacute;parer une nouvelle exp&eacute;rience. La confirmation explique la diff&eacute;rence.</p>
<h2>C. Ajouter de l'apprentissage sans perdre les poids</h2><p>Apr&egrave;s une s&eacute;ance enti&egrave;rement termin&eacute;e, <strong>Continuer l'apprentissage</strong> garde les poids et pr&eacute;pare un passage suppl&eacute;mentaire sur sa partition TRAIN, en distribution naturelle. La calibration est ensuite reconstruite sur la partition conserv&eacute;e. L'ancienne s&eacute;ance est archiv&eacute;e.</p>
<p>Les exemples CALIBRATION et TEST ne servent pas aux corrections. Les nouvelles fen&ecirc;tres entr&eacute;es depuis dans le corpus ne sont pas incluses automatiquement. C'est une continuation contr&ocirc;l&eacute;e sur le TRAIN sauvegard&eacute;, pas un apprentissage continu sur tout le flux. Au milieu du protocole, ce bouton reste bloqu&eacute; : utilise Reprendre.</p>
<p>Des poids modifi&eacute;s n'ont plus leur ancienne calibration. C'est pourquoi celle-ci est vid&eacute;e puis refaite. R&eacute;p&eacute;ter vingt fois les m&ecirc;mes exercices peut surtout renforcer leur m&eacute;morisation ; ce n'est pas vingt fois plus d'information.</p>
<h2>D. Utiliser de nouvelles dates</h2><p>Copie les observations dans le corpus, v&eacute;rifie les effectifs puis pr&eacute;pare une nouvelle exp&eacute;rience. Cette action repart d'un cerveau initial. La continuation des poids sur un corpus agrandi et un autre d&eacute;coupage n'est pas automatis&eacute;e : elle demanderait un suivi des expositions et des dates r&eacute;serv&eacute;es &agrave; l'&eacute;valuation.</p>
<h2>Un test regard&eacute; reste regard&eacute;</h2><p>Le logiciel conserve les identifiants des fen&ecirc;tres de test ouvertes dans un registre qui survit aux reprises, relectures et remises &agrave; z&eacute;ro. Si un nouveau d&eacute;coupage les reprend, un avertissement appara&icirc;t. Ce suivi concerne l'installation actuelle ; il ne prouve pas que ces donn&eacute;es n'ont jamais &eacute;t&eacute; examin&eacute;es ailleurs.</p>
<p>R&eacute;initialiser le cerveau n'efface pas ce que l'exp&eacute;rimentateur a appris des r&eacute;sultats. Choisir les param&egrave;tres en consultant le test le transforme en outil de d&eacute;veloppement. R&eacute;serve de nouvelles dates pour une v&eacute;rification finale. <a href="#s6">Principe de s&eacute;paration : S6</a>.</p>
<p class="muted">Code : Academy08.replay, continue_training, create et open_test. Les calculs de correction restent ceux d'Academy06.</p>''')
ch('debut-reset','Cerveau initial : effacer quoi, conserver quoi ?',r'''
<h1>Repartir sans perdre ses donn&eacute;es.</h1>
<p>Le projet n'a pas un seul objet &agrave; effacer. En g&eacute;n&eacute;ral, tu veux remettre une m&eacute;moire &agrave; z&eacute;ro sans supprimer les exercices qui vont l'entra&icirc;ner.</p>
<div class="table-scroll"><table><thead><tr><th>Action</th><th>Recommence</th><th>Conserve</th></tr></thead><tbody>
<tr><td>Cerveau neuf dans l'atelier</td><td>Poids, calibration, plan et compteurs de s&eacute;ance</td><td>Corpus, collecte, live, capital et archives</td></tr>
<tr><td>Rejouer depuis z&eacute;ro</td><td>Poids, calibration et progression</td><td>Plan sauvegard&eacute;, r&eacute;glages, corpus et live</td></tr>
<tr><td>Cerveau neuf sur le march&eacute;</td><td>Poids et calibration live</td><td>Portefeuille, historique financier, observations, atelier</td></tr>
<tr><td>Portefeuille &agrave; 20 &euro;</td><td>Capital et compteurs financiers de session</td><td>Poids et calibration live, corpus, atelier</td></tr>
<tr><td>Utiliser ce cerveau sur le march&eacute;</td><td>Copie live remplac&eacute;e ; session financi&egrave;re &agrave; 20 &euro;</td><td>Cerveau atelier, corpus ; ancien live archiv&eacute;</td></tr>
</tbody></table></div>
<h2>Initial ne signifie pas tous les nombres &agrave; z&eacute;ro</h2><p>Le cerveau initial conserve son architecture, sa projection d'entr&eacute;e tir&eacute;e avec la graine et ses r&egrave;gles de calcul. Les poids de touche commencent &agrave; 0,5. La lecture &eacute;conomique auxiliaire commence &agrave; z&eacute;ro. Aucune correction n'a &eacute;t&eacute; appliqu&eacute;e ; la calibration est vide. C'est un cerveau sans exp&eacute;rience apprise, pas sans structure.</p>
<p>Dans l'atelier, les r&eacute;glages du formulaire construisent le cerveau neuf. Sur le march&eacute;, le bouton reprend la taille, la graine et les capteurs de la copie live actuelle. La confirmation les affiche pour &eacute;viter de changer silencieusement d'architecture. Une m&ecirc;me graine permet de reconstruire le d&eacute;part, pas tout l'apprentissage d'un ancien cerveau.</p>
<h2>Les archives sont locales</h2><p>L'atelier range l'ancien &eacute;tat avant remplacement. Les douze derni&egrave;res archives sont t&eacute;l&eacute;chargeables. Le march&eacute; archive aussi son ancien &eacute;tat dans sa base. Ces archives ne remplacent pas une copie externe : une perte du disque peut emporter le projet et ses archives ensemble.</p>
<p>Pour remplacer le cerveau du march&eacute;, arr&ecirc;te collecte et politique et attends la fin des fen&ecirc;tres ouvertes. Le serveur refuse un remplacement pendant une fen&ecirc;tre. Les boutons demandent confirmation ; la visite guid&eacute;e n'effectue jamais une action &agrave; ta place.</p>
<h2>Ne supprime pas le volume Docker</h2><p>Il contient aussi les donn&eacute;es et les sauvegardes. Le supprimer n'est pas une fa&ccedil;on propre de recr&eacute;er un cerveau. Un checkpoint en JSON ne s'importe pas comme un corpus de fen&ecirc;tres en JSONL. Le tutoriel distingue les bons boutons sans manipulation des bases de donn&eacute;es.</p>
<p><a class="button" href="/guide#lesson-zero">Tutoriel de remise &agrave; z&eacute;ro</a> <a href="#exploitation">Fichiers persistants</a></p>''')
ch('debut-resultats','Lire les r&eacute;sultats sans se tromper',r'''
<h1>Ce qui bouge n'est pas forc&eacute;ment ce qui progresse.</h1>
<h2>Trois niveaux diff&eacute;rents</h2><p><strong>Le calcul fonctionne</strong> si les entr&eacute;es produisent des activations et les phases autoris&eacute;es corrigent les poids. <strong>Les exercices sont appris</strong> si le cerveau s'ajuste aux associations pr&eacute;sent&eacute;es. <strong>La g&eacute;n&eacute;ralisation fonctionne</strong> s'il apporte un avantage sur de nouvelles situations, sans les avoir utilis&eacute;es pour les corrections ni pour r&eacute;gler sans cesse les param&egrave;tres.</p>
<p>Un programme sans erreur peut apprendre une r&egrave;gle inutile. Un cerveau qui m&eacute;morise ses anciens exemples peut &eacute;chouer au prochain march&eacute;. Les couleurs des barres et le compteur de corrections ne suffisent pas pour passer d'une de ces affirmations &agrave; une autre.</p>
<h2>Comparer sur les m&ecirc;mes fen&ecirc;tres</h2><p>Exemple fictif : la case centrale est touch&eacute;e 60 fois sur 100. Un cerveau &agrave; 58 touches fait moins bien que toujours stable sur ce jeu, m&ecirc;me si 58 % semble &eacute;lev&eacute;. Il faut les m&ecirc;mes fen&ecirc;tres pour cette comparaison, pas une autre journ&eacute;e.</p>
<p>Le taux du curriculum &eacute;quilibr&eacute; et celui du test naturel ne portent pas sur la m&ecirc;me distribution. Une baisse entre les deux n'est pas automatiquement un bug. Observe la r&eacute;partition des choix, les exclusions et plusieurs nouvelles s&eacute;ances. Les r&eacute;sultats d'un seul petit test sont incertains.</p>
<h2>Le multiplicateur change le probl&egrave;me</h2><p>Exemple invent&eacute;, mise de 1, multiplicateur total &times;1,20 : un succ&egrave;s rapporte 0,20 net, un &eacute;chec perd 1. Avec 7 succ&egrave;s et 3 pertes, le total est 7 &times; 0,20 &minus; 3 = &minus;1,60. Un taux de r&eacute;ussite de 70 % ne suffit donc pas &agrave; assurer un b&eacute;n&eacute;fice.</p>
<p>Si la probabilit&eacute; &eacute;tait p et le multiplicateur total M, sans autre co&ucirc;t, le gain moyen par unit&eacute; serait p &times; M &minus; 1. C'est une identit&eacute; du jeu suppos&eacute;, pas un moyen de conna&icirc;tre p. Une probabilit&eacute; surestim&eacute;e ou une cotation synth&eacute;tique fausse peut faire croire &agrave; un avantage.</p>
<h2>Attendre peut &ecirc;tre une bonne d&eacute;cision</h2><p>Le cerveau fournit des scores. La calibration les relie &agrave; des fr&eacute;quences. La politique v&eacute;rifie cotation, mise et risque. Elle peut refuser de jouer m&ecirc;me si un score est meilleur que les deux autres. Toutes les options peuvent &ecirc;tre d&eacute;favorables ou insuffisamment document&eacute;es. Une attente engage z&eacute;ro et n'est pas compt&eacute;e comme victoire.</p>
<h2>La calibration n'est pas magique</h2><p>Elle regarde des groupes de scores produits par un cerveau fixe. Si les conditions changent, cette relation peut se d&eacute;grader. Avec peu d'exemples, elle reste incertaine. Les minimums du programme n'assurent pas que les probabilit&eacute;s seront correctes. <a href="#s7">Notion g&eacute;n&eacute;rale : S7</a> ; <a href="#calibration">calcul de Flytrade</a>.</p>
<h2>Un bon corpus est plus qu'un gros fichier</h2><p>Il faut la bonne source, des horaires coh&eacute;rents, le pass&eacute; avant le choix, des capteurs enregistr&eacute;s &agrave; temps et les transactions permettant de v&eacute;rifier les touches. Il faut plusieurs contextes et s&eacute;ances, pas seulement des copies d'un instant calme. Les trous, les filtrages et les refus doivent rester visibles.</p>
<p>Apr&egrave;s le choix des param&egrave;tres, garde des dates nouvelles pour le test final. Une graine heureuse, un jour favorable ou des multiplicateurs synth&eacute;tiques g&eacute;n&eacute;reux ne d&eacute;montrent pas un avantage du circuit biologique. Aucun taux magique ni effectif unique ne remplace cette comparaison.</p>''')
ch('debut-reglages','Quel r&eacute;glage changer, et pourquoi ?',r'''
<h1>Chaque r&eacute;glage est une hypoth&egrave;se d'exp&eacute;rience.</h1>
<p>Conserve les autres param&egrave;tres pour voir son effet. Archive les r&eacute;sultats et compare sur des donn&eacute;es de d&eacute;veloppement communes. Les limites exactes et les valeurs par d&eacute;faut viennent des sch&eacute;mas du serveur dans les fiches techniques.</p>
<h2>Choisir les exercices</h2><p><strong>Parcours</strong> : &eacute;quilibr&eacute; pr&eacute;sente autant de cas exclusifs par direction ; naturel garde leurs fr&eacute;quences ; curriculum commence &eacute;quilibr&eacute; puis r&eacute;introduit les autres cas. <strong>Passages</strong> : nombre de relectures. <strong>Fen&ecirc;tres r&eacute;centes maximum</strong> : sous-ensemble de travail, pas capacit&eacute; maximale du disque. <strong>M&eacute;langer TRAIN</strong> : ordre des corrections, sans changer l'ordre du test.</p>
<p>Cinq passages sur vingt exemples ne valent pas cent exemples nouveaux. &Eacute;quilibrer l'exercice ne rend pas &eacute;gales les probabilit&eacute;s r&eacute;elles du march&eacute;. Le mode naturel peut favoriser stable parce que c'est la case la plus souvent touch&eacute;e dans la p&eacute;riode.</p>
<h2>Construire le cerveau</h2><p><strong>Nombre de KC</strong> : 1 024 ou 2 048 unit&eacute;s. <strong>Fraction active</strong> : proportion approximative gard&eacute;e pour un candidat. <strong>Graine</strong> : num&eacute;ro pour refaire les m&ecirc;mes tirages. <strong>Capteurs de liquidit&eacute;</strong> : ajout du carnet connu au choix. Les exercices anciens sans carnet ne permettent pas ce mode.</p>
<p>Modifier ces param&egrave;tres demande une nouvelle exp&eacute;rience et une nouvelle calibration. Continuer ne convertit pas un cerveau de 1 024 en un cerveau de 2 048. Plus de cellules ne fournit pas plus d'information originale sur le march&eacute;.</p>
<h2>Modifier les corrections</h2><p><strong>Vitesse d'apprentissage</strong> : amplitude des ajustements. Un grand pas peut r&eacute;agir vite mais perturber ce qui &eacute;tait appris. <strong>Exploration</strong> : pendant TRAIN, chance d'essayer une case au hasard. <strong>Retour des trois touches</strong> : apprendre apr&egrave;s fermeture les trois issues ou seulement celle choisie. Cela ne donne jamais le futur avant la d&eacute;cision.</p>
<p><strong>Lecture &eacute;conomique auxiliaire</strong> : entra&icirc;ne d'autres poids si des cotations diff&eacute;r&eacute;es sont disponibles. Elle ne dimensionne pas directement les mises. <strong>Exemples par lot</strong> : travail effectu&eacute; entre deux actualisations ; cela change surtout la r&eacute;activit&eacute; de l'interface, pas les r&egrave;gles de correction.</p>
<h2>D&eacute;finir le jeu</h2><p><strong>Multiplicateurs manuels</strong> ou <strong>mode synth&eacute;tique</strong> d&eacute;finissent les versements suppos&eacute;s. <strong>Convention total/profit</strong> indique si la mise est comprise. <strong>D&eacute;lai d'ex&eacute;cution</strong> attend avant la nouvelle cotation du m&ecirc;me contrat. <strong>Slippage maximal</strong> refuse une d&eacute;gradation trop forte entre clic et verrouillage. <strong>D&eacute;cote</strong> et <strong>co&ucirc;t par mise</strong> p&eacute;nalisent le sc&eacute;nario ; ils ne sont pas des frais Euphoria authentifi&eacute;s.</p>
<p><strong>Marge synth&eacute;tique</strong>, <strong>plancher de volatilit&eacute;</strong> et <strong>multiplicateur maximal</strong> concernent notre &eacute;metteur hypoth&eacute;tique. Les changer peut cr&eacute;er un profit sans am&eacute;liorer les pr&eacute;visions. Note leurs valeurs dans chaque comparaison.</p>
<h2>Prot&eacute;ger le capital fictif</h2><p><strong>Mode de mise</strong>, <strong>mise fixe</strong>, <strong>mise maximale</strong> et <strong>fraction maximale du capital</strong> limitent les tailles admissibles. <strong>Avantage minimal</strong> impose une marge estim&eacute;e avant participation. <strong>Limite de baisse</strong> arr&ecirc;te les nouveaux engagements apr&egrave;s une perte depuis le plus haut du portefeuille.</p>
<p>Exemple de calcul : 5 % de 20 euros font 1 euro. La pr&eacute;sence de 20 euros dans la gamme ne l'autorise pas avec ce budget. Une barri&egrave;re qui emp&ecirc;che les mises n'est pas &agrave; abaisser syst&eacute;matiquement ; il faut comprendre ce qui la d&eacute;clenche.</p>
<p>Les <strong>29 champs</strong> sont d&eacute;crits individuellement dans <a href="#parametres-train">Apprentissage</a> et <a href="#parametres-risque">&Eacute;conomie et risque</a>. Ces exemples expliquent les effets, pas des valeurs optimales.</p>''')

primers={
'accueil':('Deux niveaux de lecture.','Le parcours D&eacute;buter explique les mots et les actions. Les chapitres techniques gardent les formules et les limites. Le tutoriel montre les boutons dans ton installation.'),
'carte':('Suivre le trajet des informations.','Le prix entre, les capteurs le r&eacute;sument, les KC repr&eacute;sentent le contexte et les sorties donnent des scores. Calibration et r&egrave;gles du portefeuille interviennent ensuite : elles ne sont pas des neurones.'),
'neurones':('Une case lumineuse est un calcul actif.','Le compteur instantan&eacute; n\'est pas le nombre total de cellules utilis&eacute;es depuis le d&eacute;but. Le seuil APL limite l\'activit&eacute; par contexte ; d\'autres cellules peuvent servir ailleurs.'),
'motifs':('Des noms biologiques, des calculs synth&eacute;tiques.','Les modules empruntent leurs noms &agrave; des circuits &eacute;tudi&eacute;s. Leurs vitesses et &eacute;quations sont des choix du programme. Le nom d\'un circuit ne prouve pas sa reproduction ni son utilit&eacute; financi&egrave;re.'),
'plasticite':('Apprendre veut dire modifier des poids.','La correction utilise le r&eacute;sultat apr&egrave;s le choix. Une pause conserve la m&eacute;moire ; un cerveau neuf la r&eacute;initialise. En live, les barres peuvent varier alors que les poids restent gel&eacute;s.'),
'capteurs':('Le cerveau lit des nombres, pas l\'image.','Chaque entr&eacute;e doit &ecirc;tre connue avant la d&eacute;cision. Un carnet manquant ne doit pas &ecirc;tre remplac&eacute; par le carnet du futur ou par une valeur invent&eacute;e.'),
'dataset':('Questions et corrections sont s&eacute;par&eacute;es.','L\'environnement garde le futur pour corriger ensuite, mais le cerveau ne le lit pas avant son choix. Doublons et chevauchements diminuent l\'information r&eacute;ellement nouvelle.'),
'protocoles':('Le protocole est un plan.','TRAIN corrige ; CALIBRATION mesure le sens des scores ; TEST v&eacute;rifie sans corriger. Rejouer refait le plan depuis z&eacute;ro. Continuer garde les poids pour un passage sur le TRAIN sauvegard&eacute;.'),
'calibration':('Relier un score &agrave; une fr&eacute;quence observ&eacute;e.','On regroupe des scores comparables et compte les touches sur d\'autres exemples. Trop peu de cas donne une estimation incertaine. Changer les poids rend l\'ancienne calibration inadapt&eacute;e.'),
'economie':('Gagner souvent ne suffit pas.','De petits versements peuvent &ecirc;tre annul&eacute;s par quelques pertes. Il faut prendre en compte mise, versement, co&ucirc;ts et incertitude. Nos cotations synth&eacute;tiques ne sont pas celles d\'Euphoria.'),
'execution':('Choisir, confirmer et r&eacute;gler sont trois instants.','Le multiplicateur est recalcul&eacute; apr&egrave;s le d&eacute;lai pour le contrat d&eacute;j&agrave; choisi. Une proposition mobile n\'est pas un contrat que l\'on peut d&eacute;placer apr&egrave;s coup.'),
'risque':('Limiter les engagements du portefeuille.','La politique peut attendre ou choisir une mise admissible. Les protections ne rendent pas la pr&eacute;vision plus juste et ne garantissent pas le profit.'),
'parametres-train':('Le formulaire agit &agrave; la pr&eacute;paration.','Changer un champ ne modifie pas une s&eacute;ance d&eacute;j&agrave; pr&eacute;par&eacute;e. Rejouer reprend ses r&eacute;glages sauvegard&eacute;s ; Pr&eacute;parer utilise ceux du formulaire.'),
'parametres-risque':('Ces champs d&eacute;finissent le jeu.','Ils peuvent rendre le profit simul&eacute; plus facile sans changer les neurones. Garde leurs valeurs pour comparer les exp&eacute;riences.'),
'constantes':('Certains choix sont fix&eacute;s dans le code.','Cette page explique les limites qui ne sont pas toutes dans les formulaires. Ne confonds pas secondes du march&eacute;, cadence de l\'interface et unit&eacute;s abstraites du mod&egrave;le.'),
'flux':('Connexion active ne signifie pas transaction nouvelle.','Les horloges du flux, du dernier trade et du contr&ocirc;le HTTP sont s&eacute;par&eacute;es. Une r&eacute;ponse HTTP r&eacute;p&eacute;t&eacute;e ne fabrique pas une touche.'),
'usage':('Le tutoriel montre les actions actuelles.','Pr&eacute;parer recommence &agrave; z&eacute;ro ; Reprendre conserve la position ; Continuer garde les poids. La copie vers le march&eacute; reste un transfert explicite.'),
'exploitation':('Les donn&eacute;es sont dans un volume persistant.','Le dossier de code ne contient pas forc&eacute;ment les poids du conteneur. Le script sauvegarde code et donn&eacute;es. Ne supprime pas ce volume pour recr&eacute;er un cerveau.'),
'calculs':('Ces calculateurs sont des exercices.','Les modifier ne change pas les param&egrave;tres du laboratoire. Un r&eacute;sultat de formule n\'est pas une validation des hypoth&egrave;ses entr&eacute;es.'),
'glossaire':('Pas besoin de tout m&eacute;moriser.','Reviens &agrave; ce lexique lorsqu\'un mot bloque. Le nom d\'une variable et un terme biologique proche ne d&eacute;crivent pas forc&eacute;ment la m&ecirc;me chose.'),
'sources':('Recherche et code ont des r&ocirc;les diff&eacute;rents.','Les publications fournissent l\'inspiration et les observations biologiques. Les fichiers Python donnent les calculs ex&eacute;cut&eacute;s. Aucune publication cit&eacute;e ne valide le profit de Flytrade.')}
for key,(title,text) in primers.items():
    art=soup.find('article',id=key)
    layer=BeautifulSoup(f'<section class="plain08"><span class="eyebrow">AVANT LES D&Eacute;TAILS</span><h2>{title}</h2><p>{text}</p><a href="#debut">Parcours d&eacute;butant</a> &middot; <a href="/guide">Tutoriel pratique</a></section>','html.parser')
    art.find('h1').insert_after(layer)
for key in ('usage','protocoles'):
    soup.find('article',id=key).find('h1').insert_after(BeautifulSoup('<p class="callout"><strong>Extension alpha 08 :</strong> voir <a href="#debut-reentrainer">R&eacute;entra&icirc;ner</a> pour les nouveaux boutons Rejouer et Continuer et <a href="#debut-reset">Cerveau initial</a> pour les remises &agrave; z&eacute;ro. Les formules neuronales ci-dessous sont conserv&eacute;es.</p>','html.parser'))
doc=soup.select_one('.wiki-document');newarticles=[]
for key,title,body in chapters:
    article=soup.new_tag('article',id=key,attrs={'class':'wiki-article','data-title':title})
    article.append(BeautifulSoup('<div class="article-kicker">D&Eacute;BUTER / mots simples, exemples concrets</div>'+body+'<div class="article-foot"><a href="#debut">Revenir au d&eacute;but</a><button type="button" data-copy="'+key+'">Copier le lien</button></div>','html.parser'))
    newarticles.append(article)
for art in reversed(newarticles):doc.insert(0,art)
toc=soup.select_one('.wiki-toc');toc.clear()
for i,art in enumerate(doc.select('article.wiki-article')):
    link=soup.new_tag('a',href='#'+art['id'],attrs={'data-chapter':art['id']});num=soup.new_tag('span');num.string=f'{i+1:02}';link.append(num);link.append(art['data-title']);toc.append(link)
soup.find(id='search-count').string=str(len(doc.select('article')))+' chapitres'
soup.find(id='wiki-search')['placeholder']='recommencer, cerveau neuf, calibration...'
shortcut=soup.new_tag('a',href='/guide');shortcut.string='Ouvrir le tutoriel';soup.select_one('.wiki-sidebar').insert(0,shortcut)
P.joinpath('wiki08.html').write_text(str(soup),encoding='utf-8')
js=P.joinpath('wiki07.js').read_text().replace("let key='accueil'","let key='debut'").replace("article=$('accueil')","article=$('debut')")
P.joinpath('wiki08.js').write_text(js)
plain='\n\n'.join(a['data-title']+'\n'+'='*60+'\n'+a.get_text(' ',strip=True) for a in doc.select('article'))
Path('docs/wiki/WIKI-08.txt').write_text(plain,encoding='utf-8')
print('Wiki08:',len(doc.select('article')),'chapters;',len(plain.split()),'words;',len(chapters),'beginner chapters')
